/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: `${process.env.NEXT_PUBLIC_COGNITO_REHION}`,
	aws_cognito_region: `${process.env.NEXT_PUBLIC_COGNITO_REHION}`,
	aws_user_pools_id: `${process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID}`,
	aws_user_pools_web_client_id: `${process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID}`,
	oauth: {
		domain: `${process.env.NEXT_PUBLIC_COGNITO_DOMAIN}`,
		scope: ['aws.cognito.signin.user.admin', 'email', 'openid'],
		redirectSignIn: `${process.env.NEXT_PUBLIC_COGNITO_URI}`,
		redirectSignOut: `${process.env.NEXT_PUBLIC_COGNITO_URI}`,
		responseType: 'code',
	},
	federationTarget: 'COGNITO_USER_POOLS',
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: ['GOOGLE'],
	aws_cognito_signup_attributes: ['NICKNAME', 'EMAIL'],
	aws_cognito_mfa_configuration: 'OPTIONAL',
	aws_cognito_mfa_types: ['TOTP'],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: ['REQUIRES_LOWERCASE', 'REQUIRES_UPPERCASE', 'REQUIRES_NUMBERS', 'REQUIRES_SYMBOLS'],
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
